services:
  db:
    image: postgres:latest
    container_name: computer_inventory_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: computer_admin
      POSTGRES_PASSWORD: Pass0rd1
    volumes:
      - computer_inventory_db_vol:/var/lib/postgresql/data

volumes:
  computer_inventory_db_vol: